### PR TITLE
Sorting Disjointedness

### PR DESCRIPTION
**Pull request by philarcher**
And replacing owl:unionOf with simple list of domains for isExtensible

### CODE REVIEW

**Comment by mgh128** [comment]
Is the rdfs:domain of isExtensible the intersection (logical AND) of gs1:GS1DelegatedPrefixLicenceCredential AND gs1:GS1CompanyPrefixLicenceCredential

If not, then we either need to use schema:domainIncludes or the hideously clunky mess involving owl:unionOf, as we have done in the GS1 Web vocabulary.  Such a pity that RDFS was never extended to include rangeIncludes and domainIncludes natively.

I think you might need to rework this handling of the domain for isExtensible.

**Comment by philarcher** [comment]
I take "Applies only to GS1 Delegated Prefix and GS1 Company Prefix licences" to mean logical OR, no? Those two classes are disjoint so logical AND can never be true. AS ever, I stand to be corrected but that's my reading of Kevin's text.

Separately, I think I need to add some more disjoint triples, which I'll do now.

**Comment by mgh128** [comment]
I think the written statement implies logical OR, which is why you either need to use clunky owl:unionOf with rdfs:domain or use schema:domainIncludes.

If you use rdfs:domain or rdfs:range with a list, then it means that the domain or range is simultaneously all values of the list, i.e. a logical AND, which is not what you want - which is an OR.  

You can take a look at the Turtle or JSON-LD for a property such as gs1:globalLocationNumber to see how we've used owl:unionOf - or just search for owl:unionOf.

**Comment by philarcher** [comment]
You are, as ever, correct. I now see that. OK - Occam's Razor: we just declare the domain to be the top level gs1:LicenceCredential and let SHACL take care of the rest. The alternatives are, as you say, clunky.

**Comment by mgh128** [comment]
Thanks for making that adjustment.  It's not so much SHACL as rdfs:subClassOf inferences.

**Comment by ghost** [comment]
I would prefer not to have isExtensibleLicence at the top level, as it would be the only attribute that we don't have proper range on. I would prefer to go back to the unionOf, as clunky as it may be.

**Review by ghost — APPROVED** [review]

**Comment by mgh128** [comment]
Done

**Pull request merged**
